version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "gomod"
    directory: "/examples/microservice"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "examples"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "actions"
